DROP TABLE IF EXISTS t_task ;
DROP SEQUENCE IF EXISTS seq_activity;

CREATE SEQUENCE seq_activity AS INTEGER START WITH 10000;

CREATE MEMORY TABLE t_task
(
--     id                      INTEGER DEFAULT seq_activity.nextval PRIMARY KEY,
--     id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE seq_activity PRIMARY KEY,
    id                      INTEGER PRIMARY KEY,
    title                   VARCHAR(100)    NOT NULL,
    description             VARCHAR(1000),
    activity_datetime       TIMESTAMP,
    created                 TIMESTAMP       NOT NULL,
    modified                TIMESTAMP       NOT NULL
);
